services:
  postojka:
    build:
      context: .
    container_name: postojka
    ports:
      - "8002:8000"
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postojka_db
    environment:
      POSTGRES_DB: postojka_db
      POSTGRES_USER: postojka_user
      POSTGRES_PASSWORD: postojka_pass
    volumes:
      - postojka_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postojka_pgdata: